### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Leverpostej** [Huises/FAWDN#1]
Hello

As i understand from the readme there should be 3 .json files in the Options/test folder:
test_FAWDN_x2.json, 
test_FAWDN_x3.json, 
test_FAWDN_x4.json

However none of these files are there. Is it possible you can upload them?

Best Regards
Tobias

**Comment by Lihui-Chen** [comment]
These files have been uploaded. You can get them in the ./options/test/ folder.
