### ISSUE TITLE
Training new models

### ISSUE THREAD

**Issue by NCJ1994** [Huises/FAWDN#2]
Hi

We want to try and train a new FAWDN model with another dataset of images.
We are having some issues figuring out how the do this. The error we are getting right now is show below:
![image](https://user-images.githubusercontent.com/72389245/116534237-902ee600-a8e2-11eb-92b7-c867f8d3c20b.png)
From what we can read, it has something to do with batch size etc. We lower that to avoid running out of memory, and reducing it enough will give that error.
We are in doubt how the dataset should look like. What images can we use?
This is an example of an image we try and use
![mrispine](https://user-images.githubusercontent.com/72389245/116534599-059ab680-a8e3-11eb-90a7-bde9c6f71563.jpg)
This is the train options file we are trying.
https://pastebin.com/TJbL2W67

Hope that you can help us

**Comment by Lihui-Chen** [comment]
Hi

This error indicates that the size of HR images is 30×30 while that of SR is 120×120, which results in dimension mismatch for calculating the loss. The size of HR images should be ×(scale) that of the LR images in your dataset, as FWADN produces SR images of the size that is ×(scale) of the size of the input LR images.

**Comment by NCJ1994** [comment]
Thank you very much
